[package]
name = "universal-film-camera"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "universal_film_camera_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
camera-core.workspace = true
camera-apple.workspace = true
film-core.workspace = true
imaging-core.workspace = true
serde.workspace = true
tauri = { version = "2", features = [] }
