[package]
name = "camera-apple"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
camera-core.workspace = true

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
block2 = "0.6.2"
objc2 = "0.6.4"
objc2-av-foundation = { version = "0.3.2", features = ["AVAnimation", "AVCaptureDevice", "AVCaptureFileOutput", "AVCaptureInput", "AVCaptureOutputBase", "AVCapturePhotoOutput", "AVCaptureSession", "AVCaptureSessionPreset", "AVCaptureVideoPreviewLayer", "AVMediaFormat", "block2", "objc2-core-media", "objc2-quartz-core"] }
objc2-core-media = { version = "0.3.2", features = ["CMFormatDescription"] }
objc2-foundation = { version = "0.3.2", features = ["NSArray", "NSData", "NSDictionary", "NSError", "NSObject", "NSString", "NSURL"] }
objc2-quartz-core = { version = "0.3.2", features = ["CALayer"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2-app-kit = { version = "0.3.2", features = ["NSResponder", "NSView", "NSWindow", "objc2-quartz-core"] }
